clc;
x1=input('enter the first sequence');
x2=input('enter the second sequence');
subplot(3,1,1);
stem(x1);
ylabel('amplitude');
title('plot the first sequence');
subplot(3,1,2);
stem(x2);
ylabel('amplitude');
title('plot the second sequence');
f=conv(x1,x2);
disp('output of linear convolution is');
disp(f);
xlabel('time index n');
ylabel('amplitude f');
subplot(3,1,3);
stem(f);
title('linear covolution of sequence');
